name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: ckomop0x/shared-workflows/.github/workflows/unit-tests.yml@main
    with:
      node_version: '24'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
